"use client"

import { useState } from "react"
import { Check, ChevronsUpDown } from "lucide-react"
import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from "@/components/ui/command"
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover"

interface FontSelectorProps {
  value: string
  onChange: (value: string) => void
}

// All fonts available to everyone
const ALL_FONTS = [
  { value: "var(--font-inter)", label: "Inter" },
  { value: "var(--font-roboto)", label: "Roboto" },
  { value: "var(--font-lato)", label: "Lato" },
  { value: "var(--font-montserrat)", label: "Montserrat" },
  { value: "var(--font-oswald)", label: "Oswald" },
  { value: "var(--font-pacifico)", label: "Pacifico" },
  { value: "var(--font-playfair-display)", label: "Playfair Display" },
  { value: "var(--font-dancing-script)", label: "Dancing Script" },
  { value: "var(--font-hind-siliguri)", label: "Hind Siliguri" },
  { value: "var(--font-ubuntu)", label: "Ubuntu" },
  { value: "var(--font-merriweather)", label: "Merriweather" },
  { value: "var(--font-kanit)", label: "Kanit" },
  { value: "var(--font-big-shoulders-display)", label: "Big Shoulders Display" },
  { value: "var(--font-dm-sans)", label: "DM Sans" },
  // { value: "var(--font-mulish)", label: "Mulish" },
  // { value: "var(--font-bebas-neue)", label: "Bebas Neue" },
  // { value: "var(--font-outfit)", label: "Outfit" },
  // { value: "var(--font-anton)", label: "Anton" },
  // { value: "var(--font-mukta)", label: "Mukta" },
  // { value: "var(--font-teko)", label: "Teko" },
  // { value: "var(--font-hind)", label: "Hind" },
  // { value: "var(--font-rowdies)", label: "Rowdies" },
  // { value: "var(--font-lobster)", label: "Lobster" },
  // { value: "var(--font-noto-sans-arabic)", label: "Noto Sans Arabic" },
  // { value: "var(--font-caveat)", label: "Caveat" },
  // { value: "var(--font-rajdhani)", label: "Rajdhani" },
  // { value: "var(--font-ibm-plex-mono)", label: "IBM Plex Mono" },
  // { value: "var(--font-fjalla-one)", label: "Fjalla One" },
  // { value: "var(--font-noto-sans-thai)", label: "Noto Sans Thai" },
  // { value: "var(--font-shadows-into-light)", label: "Shadows Into Light" },
  // { value: "var(--font-satisfy)", label: "Satisfy" },
  // { value: "var(--font-nanum-gothic-coding)", label: "Nanum Gothic Coding" },
  // { value: "var(--font-permanent-marker)", label: "Permanent Marker" },
  // { value: "var(--font-indie-flower)", label: "Indie Flower" },
  // { value: "var(--font-nanum-myeongjo)", label: "Nanum Myeongjo" },
  // { value: "var(--font-ibm-plex-sans-arabic)", label: "IBM Plex Sans Arabic" },
  // { value: "var(--font-oleo-script)", label: "Oleo Script" },
  // { value: "var(--font-orbitron)", label: "Orbitron" },
  // { value: "var(--font-amatic-sc)", label: "Amatic SC" },
  // { value: "var(--font-great-vibes)", label: "Great Vibes" },
  // { value: "var(--font-rock-salt)", label: "Rock Salt" },
  // { value: "var(--font-courgette)", label: "Courgette" },
  // { value: "var(--font-bangers)", label: "Bangers" },
  // { value: "var(--font-yellowtail)", label: "Yellowtail" },
  // { value: "var(--font-lobster-two)", label: "Lobster Two" },
  // { value: "var(--font-kaushan-script)", label: "Kaushan Script" },
  // { value: "var(--font-rochester)", label: "Rochester" },
  // { value: "var(--font-sacramento)", label: "Sacramento" },
  // { value: "var(--font-allura)", label: "Allura" },
  // { value: "var(--font-gravitas-one)", label: "Gravitas One" },
  // { value: "var(--font-noto-sans-bengali)", label: "Noto Sans Bengali" },
  // { value: "var(--font-sofia)", label: "Sofia" },
  // { value: "var(--font-monoton)", label: "Monoton" },
  // { value: "var(--font-fugaz-one)", label: "Fugaz One" },
  // { value: "var(--font-special-elite)", label: "Special Elite" },
  // { value: "var(--font-berkshire-swash)", label: "Berkshire Swash" },
  // { value: "var(--font-tangerine)", label: "Tangerine" },
  // { value: "var(--font-poiret-one)", label: "Poiret One" },
  // { value: "var(--font-geologica)", label: "Geologica" },
  // { value: "var(--font-monsieur-la-doulaise)", label: "Monsieur La Doulaise" },
  // { value: "var(--font-ropa-sans)", label: "Ropa Sans" },
  // { value: "var(--font-alice)", label: "Alice" },
  // { value: "var(--font-mr-dafoe)", label: "Mr Dafoe" },
  // { value: "var(--font-handlee)", label: "Handlee" },
  // { value: "var(--font-homemade-apple)", label: "Homemade Apple" },
  // { value: "var(--font-alex-brush)", label: "Alex Brush" },
  // { value: "var(--font-spicy-rice)", label: "Spicy Rice" },
  // { value: "var(--font-marck-script)", label: "Marck Script" },
  // { value: "var(--font-bad-script)", label: "Bad Script" },
  // { value: "var(--font-playball)", label: "Playball" },
  // { value: "var(--font-pinyon-script)", label: "Pinyon Script" },
  // { value: "var(--font-ibm-plex-sans)", label: "IBM Plex Sans" },
  // { value: "var(--font-red-rose)", label: "Red Rose" },
  // { value: "var(--font-edu-au-vic-wa-nt-hand)", label: "Edu AU VIC WA NT Hand" },
  // { value: "var(--font-unifraktur-maguntia)", label: "Unifraktur Maguntia" },
  // { value: "var(--font-doto)", label: "Doto" },
  // { value: "var(--font-instrument-serif)", label: "Instrument Serif" },
  // { value: "var(--font-quintessential)", label: "Quintessential" },
  // { value: "var(--font-seaweed-script)", label: "Seaweed Script" },
  // { value: "var(--font-biryani)", label: "Biryani" },
  // { value: "var(--font-mouse-memoirs)", label: "Mouse Memoirs" },
  // { value: "var(--font-rubik-burned)", label: "Rubik Burned" },
  // { value: "var(--font-style-script)", label: "Style Script" },
  // { value: "var(--font-skranji)", label: "Skranji" },
  // { value: "var(--font-bubblegum-sans)", label: "Bubblegum Sans" },
  // { value: "var(--font-prosto-one)", label: "Prosto One" },
  // { value: "var(--font-mansalva)", label: "Mansalva" },
  // { value: "var(--font-im-fell-english)", label: "IM Fell English" },
  // { value: "var(--font-meddon)", label: "Meddon" },
  // { value: "var(--font-caprasimo)", label: "Caprasimo" },
  // { value: "var(--font-delius-unicase)", label: "Delius Unicase" },
  // { value: "var(--font-ruslan-display)", label: "Ruslan Display" },
  // { value: "var(--font-qwigley)", label: "Qwigley" },
  // { value: "var(--font-mr-de-haviland)", label: "Mr De Haviland" },
  // { value: "var(--font-whisper)", label: "Whisper" },
  // { value: "var(--font-mountains-of-christmas)", label: "Mountains of Christmas" },
  // { value: "var(--font-aguafina-script)", label: "Aguafina Script" },
  // { value: "var(--font-poetsen-one)", label: "Poetsen One" },
  // { value: "var(--font-megrim)", label: "Megrim" },
  // { value: "var(--font-rouge-script)", label: "Rouge Script" },
  // { value: "var(--font-red-rose)", label: "Red Rose" },
  // { value: "var(--font-hurricane)", label: "Hurricane" },
  // { value: "var(--font-tiro-bangla)", label: "Tiro Bangla" },
  // { value: "var(--font-margarine)", label: "Margarine" },
  // { value: "var(--font-voltaire)", label: "Voltaire" },
  // { value: "var(--font-anybody)", label: "Anybody" },
  // { value: "var(--font-oregano)", label: "Oregano" },
  // { value: "var(--font-madimi-one)", label: "Madimi One" },
  // { value: "var(--font-mogra)", label: "Mogra" },
  // { value: "var(--font-cambo)", label: "Cambo" },
  // { value: "var(--font-sansita-swashed)", label: "Sansita Swashed" },
  // { value: "var(--font-share-tech)", label: "Share Tech" },
  // { value: "var(--font-fondamento)", label: "Fondamento" },
  // { value: "var(--font-aladin)", label: "Aladin" },
  // { value: "var(--font-quando)", label: "Quando" },
  // { value: "var(--font-amarante)", label: "Amarante" },
  // { value: "var(--font-fuggles)", label: "Fuggles" },
  // { value: "var(--font-wind-song)", label: "Wind Song" },
  // { value: "var(--font-give-you-glory)", label: "Give You Glory" },
  // { value: "var(--font-chivo-mono)", label: "Chivo Mono" },
  // { value: "var(--font-asul)", label: "Asul" },
  // { value: "var(--font-allan)", label: "Allan" },
  // { value: "var(--font-monte-carlo)", label: "Monte Carlo" },
  // { value: "var(--font-montez)", label: "Montez" },
  // { value: "var(--font-happy-monkey)", label: "Happy Monkey" },
  // { value: "var(--font-federo)", label: "Federo" },
  // { value: "var(--font-sue-ellen-francisco)", label: "Sue Ellen Francisco" },
  // { value: "var(--font-almendra)", label: "Almendra" },
  // { value: "var(--font-poller-one)", label: "Poller One" },
  // { value: "var(--font-delicious-handrawn)", label: "Delicious Handrawn" },
  // { value: "var(--font-reddit-mono)", label: "Reddit Mono" },
  // { value: "var(--font-chela-one)", label: "Chela One" },
  // { value: "var(--font-suranna)", label: "Suranna" },
  // { value: "var(--font-sedgwick-ave)", label: "Sedgwick Ave" },
  // { value: "var(--font-vibur)", label: "Vibur" },
  // { value: "var(--font-salsa)", label: "Salsa" },
  // { value: "var(--font-cutive)", label: "Cutive" },
  // { value: "var(--font-croissant-one)", label: "Croissant One" },
  // { value: "var(--font-brawler)", label: "Brawler" },
  // { value: "var(--font-tienne)", label: "Tienne" },
  // { value: "var(--font-ar-one-sans)", label: "AR One Sans" },
  // { value: "var(--font-supermercado-one)", label: "Supermercado One" },
  // { value: "var(--font-inknut-antiqua)", label: "Inknut Antiqua" },
  // { value: "var(--font-coiny)", label: "Coiny" },
  // { value: "var(--font-euphoria-script)", label: "Euphoria Script" },
  // { value: "var(--font-walter-turncoat)", label: "Walter Turncoat" },
  // { value: "var(--font-zen-antique-soft)", label: "Zen Antique Soft" },
  // { value: "var(--font-zen-dots)", label: "Zen Dots" },
  // { value: "var(--font-numans)", label: "Numans" },
  // { value: "var(--font-sumana)", label: "Sumana" },
  // { value: "var(--font-xanh-mono)", label: "Xanh Mono" },
  // { value: "var(--font-protest-revolution)", label: "Protest Revolution" },
  // { value: "var(--font-edu-au-vic-wa-nt-dots)", label: "Edu AU VIC WA NT Dots" },
  // { value: "var(--font-orelega-one)", label: "Orelega One" },
  // { value: "var(--font-meow-script)", label: "Meow Script" },
  // { value: "var(--font-loved-by-the-king)", label: "Loved by the King" },
  // { value: "var(--font-ephesis)", label: "Ephesis" },
  // { value: "var(--font-unkempt)", label: "Unkempt" },
  // { value: "var(--font-corinthia)", label: "Corinthia" },
  // { value: "var(--font-crafty-girls)", label: "Crafty Girls" },
  // { value: "var(--font-dynapuff)", label: "DynaPuff" },
  // { value: "var(--font-atma)", label: "Atma" },
  // { value: "var(--font-montaga)", label: "Montaga" },
  // { value: "var(--font-oleo-script-swash-caps)", label: "Oleo Script Swash Caps" },
  // { value: "var(--font-im-fell-double-pica)", label: "IM Fell Double Pica" },
  // { value: "var(--font-bilbo-swash-caps)", label: "Bilbo Swash Caps" },
  // { value: "var(--font-kranky)", label: "Kranky" },
  // { value: "var(--font-puritan)", label: "Puritan" },
  // { value: "var(--font-charmonman)", label: "Charmonman" },
  // { value: "var(--font-carme)", label: "Carme" },
  // { value: "var(--font-rhodium-libre)", label: "Rhodium Libre" },
  // { value: "var(--font-just-me-again-down-here)", label: "Just Me Again Down Here" },
  // { value: "var(--font-lilita-one)", label: "Lilita One" },
  // { value: "var(--font-lily-script-one)", label: "Lily Script One" },
  // { value: "var(--font-dekko)", label: "Dekko" },
  // { value: "var(--font-slabo-13px)", label: "Slabo 13px" },
  // { value: "var(--font-shojumaru)", label: "Shojumaru" },
  // { value: "var(--font-notable)", label: "Notable" },
  // { value: "var(--font-gentium-plus)", label: "Gentium Plus" },
  // { value: "var(--font-fontdiner-swanky)", label: "Fontdiner Swanky" },
  // { value: "var(--font-sarina)", label: "Sarina" },
  // { value: "var(--font-elsie)", label: "Elsie" },
  // { value: "var(--font-saira-stencil-one)", label: "Saira Stencil One" },
  // { value: "var(--font-anaheim)", label: "Anaheim" },
  // { value: "var(--font-bellota)", label: "Bellota" },
  // { value: "var(--font-fragment-mono)", label: "Fragment Mono" },
  // { value: "var(--font-slackey)", label: "Slackey" },
  // { value: "var(--font-clicker-script)", label: "Clicker Script" },
  // { value: "var(--font-artifika)", label: "Artifika" },
  // { value: "var(--font-sofadi-one)", label: "Sofadi One" },
  // { value: "var(--font-duru-sans)", label: "Duru Sans" },
  // { value: "var(--font-mako)", label: "Mako" },
  // { value: "var(--font-platypi)", label: "Platypi" },
  // { value: "var(--font-the-girl-next-door)", label: "The Girl Next Door" },
  // { value: "var(--font-carlito)", label: "Carlito" },
  // { value: "var(--font-island-moments)", label: "Island Moments" },
  // { value: "var(--font-doppio-one)", label: "Doppio One" },
  // { value: "var(--font-metamorphous)", label: "Metamorphous" },
  // { value: "var(--font-bigshot-one)", label: "Bigshot One" },
  // { value: "var(--font-balthazar)", label: "Balthazar" },
  // { value: "var(--font-dynalight)", label: "Dynalight" },
  // { value: "var(--font-nova-round)", label: "Nova Round" },
  // { value: "var(--font-fustat)", label: "Fustat" },
  // { value: "var(--font-rubik-dirt)", label: "Rubik Dirt" },
  // { value: "var(--font-bakbak-one)", label: "Bakbak One" },
  // { value: "var(--font-prociono)", label: "Prociono" },
  // { value: "var(--font-nerko-one)", label: "Nerko One" },
  // { value: "var(--font-radio-canada)", label: "Radio Canada" },
  // { value: "var(--font-redressed)", label: "Redressed" },
  // { value: "var(--font-square-peg)", label: "Square Peg" },
  // { value: "var(--font-sail)", label: "Sail" },
  // { value: "var(--font-shanti)", label: "Shanti" },
  // { value: "var(--font-scheherazade-new)", label: "Scheherazade New" },
  // { value: "var(--font-wire-one)", label: "Wire One" },
  // { value: "var(--font-germania-one)", label: "Germania One" },
  // { value: "var(--font-jersey-25)", label: "Jersey 25" },
  // { value: "var(--font-henny-penny)", label: "Henny Penny" },
  // { value: "var(--font-lacquer)", label: "Lacquer" },
  // { value: "var(--font-chicle)", label: "Chicle" },
  // { value: "var(--font-noto-serif-ahom)", label: "Noto Serif Ahom" },
  // { value: "var(--font-mirza)", label: "Mirza" },
  // { value: "var(--font-medieval-sharp)", label: "Medieval Sharp" },
  // { value: "var(--font-galada)", label: "Galada" },
  // { value: "var(--font-road-rage)", label: "Road Rage" },
  // { value: "var(--font-licorice)", label: "Licorice" },
  // { value: "var(--font-overlock-sc)", label: "Overlock SC" },
  // { value: "var(--font-viaoda-libre)", label: "Viaoda Libre" },
  // { value: "var(--font-manuale)", label: "Manuale" },
  // { value: "var(--font-convergence)", label: "Convergence" },
  // { value: "var(--font-vujahday-script)", label: "Vujahday Script" },
  // { value: "var(--font-peralta)", label: "Peralta" },
  // { value: "var(--font-life-savers)", label: "Life Savers" },
  // { value: "var(--font-genos)", label: "Genos" },
  // { value: "var(--font-eagle-lake)", label: "Eagle Lake" },
  // { value: "var(--font-akaya-kanadaka)", label: "Akaya Kanadaka" },
  // { value: "var(--font-arima)", label: "Arima" },
  // { value: "var(--font-reggae-one)", label: "Reggae One" },
  // { value: "var(--font-orienta)", label: "Orienta" },
  // { value: "var(--font-modern-antiqua)", label: "Modern Antiqua" },
  // { value: "var(--font-bubbler-one)", label: "Bubbler One" },
  // { value: "var(--font-original-surfer)", label: "Original Surfer" },
  // { value: "var(--font-carattere)", label: "Carattere" },
  // { value: "var(--font-sedgwick-ave-display)", label: "Sedgwick Ave Display" },
  // { value: "var(--font-iceland)", label: "Iceland" },
  // { value: "var(--font-iceberg)", label: "Iceberg" },
  // { value: "var(--font-vampiro-one)", label: "Vampiro One" },
  // { value: "var(--font-kablammo)", label: "Kablammo" },
  // { value: "var(--font-flamenco)", label: "Flamenco" },
  // { value: "var(--font-crushed)", label: "Crushed" },
  // { value: "var(--font-bona-nova)", label: "Bona Nova" },
  // { value: "var(--font-borel)", label: "Borel" },
  // { value: "var(--font-homenaje)", label: "Homenaje" },
  // { value: "var(--font-kavivanar)", label: "Kavivanar" },
  // { value: "var(--font-moderustic)", label: "Moderustic" },
  // { value: "var(--font-belgrano)", label: "Belgrano" },
  // { value: "var(--font-swanky-and-moo-moo)", label: "Swanky and Moo Moo" },
  // { value: "var(--font-macondo-swash-caps)", label: "Macondo Swash Caps" },
  // { value: "var(--font-sunshiney)", label: "Sunshiney" },
  // { value: "var(--font-medula-one)", label: "Medula One" },
  // { value: "var(--font-alkalami)", label: "Alkalami" },
  // { value: "var(--font-frijole)", label: "Frijole" },
  // { value: "var(--font-sulphur-point)", label: "Sulphur Point" },
  // { value: "var(--font-edu-sa-beginner)", label: "Edu SA Beginner" },
  // { value: "var(--font-trade-winds)", label: "Trade Winds" },
  // { value: "var(--font-ceviche-one)", label: "Ceviche One" },
  // { value: "var(--font-bhu-tuka-expanded-one)", label: "Bhu Tuka Expanded One" },
  // { value: "var(--font-rationale)", label: "Rationale" },
  // { value: "var(--font-baumans)", label: "Baumans" },
  // { value: "var(--font-mate-sc)", label: "Mate SC" },
  // { value: "var(--font-cherry-swash)", label: "Cherry Swash" },
  // { value: "var(--font-beth-ellen)", label: "Beth Ellen" },
  // { value: "var(--font-the-nautigal)", label: "The Nautigal" },
  // { value: "var(--font-delius-swash-caps)", label: "Delius Swash Caps" },
  // { value: "var(--font-kavoon)", label: "Kavoon" },
  // { value: "var(--font-nosifer)", label: "Nosifer" },
  // { value: "var(--font-comforter-brush)", label: "Comforter Brush" },
  // { value: "var(--font-protest-strike)", label: "Protest Strike" },
  // { value: "var(--font-new-amsterdam)", label: "New Amsterdam" },
  // { value: "var(--font-rum-raisin)", label: "Rum Raisin" },
  // { value: "var(--font-strait)", label: "Strait" },
  // { value: "var(--font-miniver)", label: "Miniver" },
  // { value: "var(--font-sonsie-one)", label: "Sonsie One" },
  // { value: "var(--font-mate)", label: "Mate" },
  // { value: "var(--font-lexend-mega)", label: "Lexend Mega" },
  // { value: "var(--font-fuzzy-bubbles)", label: "Fuzzy Bubbles" },
  // { value: "var(--font-uncial-antiqua)", label: "Uncial Antiqua" },
  // { value: "var(--font-jersey-15)", label: "Jersey 15" },
  // { value: "var(--font-rosarivo)", label: "Rosarivo" },
  // { value: "var(--font-freckle-face)", label: "Freckle Face" },
  // { value: "var(--font-ruthie)", label: "Ruthie" },
  // { value: "var(--font-nova-slim)", label: "Nova Slim" },
  // { value: "var(--font-voces)", label: "Voces" },
  // { value: "var(--font-stick)", label: "Stick" },
  // { value: "var(--font-gentium-book-plus)", label: "Gentium Book Plus" },
  // { value: "var(--font-combo)", label: "Combo" },
  // { value: "var(--font-send-flowers)", label: "Send Flowers" },
  // { value: "var(--font-vibes)", label: "Vibes" },
  // { value: "var(--font-bahiana)", label: "Bahiana" },
  // { value: "var(--font-bahianita)", label: "Bahianita" },
  // { value: "var(--font-my-soul)", label: "My Soul" },
  // { value: "var(--font-taprom)", label: "Taprom" },
  // { value: "var(--font-love-light)", label: "Love Light" },
  // { value: "var(--font-langar)", label: "Langar" },
  // { value: "var(--font-protest-guerrilla)", label: "Protest Guerrilla" },
  // { value: "var(--font-kings)", label: "Kings" },
  // { value: "var(--font-splash)", label: "Splash" },
  // { value: "var(--font-geostar-fill)", label: "Geostar Fill" },
  // { value: "var(--font-suravaram)", label: "Suravaram" },
  // { value: "var(--font-hedvig-letters-sans)", label: "Hedvig Letters Sans" },
  // { value: "var(--font-rubik-spray-paint)", label: "Rubik Spray Paint" },
  // { value: "var(--font-zen-loop)", label: "Zen Loop" },
  // { value: "var(--font-snowburst-one)", label: "Snowburst One" },
  // { value: "var(--font-m-plus-1)", label: "M PLUS 1" },
  // { value: "var(--font-grechen-fuemen)", label: "Grechen Fuemen" },
  // { value: "var(--font-tapestry)", label: "Tapestry" },
  // { value: "var(--font-syne-tactile)", label: "Syne Tactile" },
  // { value: "var(--font-petemoss)", label: "Petemoss" },
  // { value: "var(--font-are-you-serious)", label: "Are You Serious" },
  // { value: "var(--font-estonia)", label: "Estonia" },
  // { value: "var(--font-nunito)", label: "Nunito" },
  // { value: "var(--font-rubik)", label: "Rubik" },
  // { value: "var(--font-playfair)", label: "Playfair" },
  // { value: "var(--font-playfair-display-sc)", label: "Playfair Display SC" },
  // { value: "var(--font-roboto-slab)", label: "Roboto Slab" },
  // { value: "var(--font-pt-sans)", label: "PT Sans" },
  // { value: "var(--font-noto-color-emoji)", label: "Noto Color Emoji" },
  // { value: "var(--font-hind-madurai)", label: "Hind Madurai" },
  // { value: "var(--font-schibsted-grotesk)", label: "Schibsted Grotesk" },
  // { value: "var(--font-figtree)", label: "Figtree" },
  // { value: "var(--font-source-code-pro)", label: "Source Code Pro" },
  // { value: "var(--font-prompt)", label: "Prompt" },
  // { value: "var(--font-archivo)", label: "Archivo" },
  // { value: "var(--font-cabin)", label: "Cabin" },
  // { value: "var(--font-antonio)", label: "Antonio" },
  // { value: "var(--font-dosis)", label: "Dosis" },
  // { value: "var(--font-exo-2)", label: "Exo 2" },
  // { value: "var(--font-plus-jakarta-sans)", label: "Plus Jakarta Sans" },
  // { value: "var(--font-tektur)", label: "Tektur" },
  // { value: "var(--font-public-sans)", label: "Public Sans" },
  // { value: "var(--font-assistant)", label: "Assistant" },
  // { value: "var(--font-roboto-flex)", label: "Roboto Flex" },
  // { value: "var(--font-lexend-deca)", label: "Lexend Deca" },
  // { value: "var(--font-abel)", label: "Abel" },
  // { value: "var(--font-overpass)", label: "Overpass" },
  // { value: "var(--font-arvo)", label: "Arvo" },
  // { value: "var(--font-fjord-one)", label: "Fjord One" },
  // { value: "var(--font-cormorant-infant)", label: "Cormorant Infant" },
  // { value: "var(--font-signika-negative)", label: "Signika Negative" },
  // { value: "var(--font-saira)", label: "Saira" },
  // { value: "var(--font-noto-music)", label: "Noto Music" },
  // { value: "var(--font-fira-sans-condensed)", label: "Fira Sans Condensed" },
  // { value: "var(--font-staatliches)", label: "Staatliches" },
  // { value: "var(--font-be-vietnam-pro)", label: "Be Vietnam Pro" },
  // { value: "var(--font-play)", label: "Play" },
  // { value: "var(--font-chakra-petch)", label: "Chakra Petch" },
  // { value: "var(--font-merriweather-sans)", label: "Merriweather Sans" },
  // { value: "var(--font-petit-formal-script)", label: "Petit Formal Script" },
  // { value: "var(--font-questrial)", label: "Questrial" },
  // { value: "var(--font-ibm-plex-sans)", label: "IBM Plex Sans" },
  // { value: "var(--font-inter-tight)", label: "Inter Tight" },
  // { value: "var(--font-source-serif-4)", label: "Source Serif 4" },
  // { value: "var(--font-frank-ruhl-libre)", label: "Frank Ruhl Libre" },
  // { value: "var(--font-smooch-sans)", label: "Smooch Sans" },
  // { value: "var(--font-domine)", label: "Domine" },
  // { value: "var(--font-cinzel)", label: "Cinzel" },
  // { value: "var(--font-vollkorn)", label: "Vollkorn" },
  // { value: "var(--font-passion-one)", label: "Passion One" },
  // { value: "var(--font-lexend-exa)", label: "Lexend Exa" },
  // { value: "var(--font-catamaran)", label: "Catamaran" },
  // { value: "var(--font-marcellus)", label: "Marcellus" },
  // { value: "var(--font-signika)", label: "Signika" },
  // { value: "var(--font-archivo-narrow)", label: "Archivo Narrow" },
  // { value: "var(--font-rubik-beastly)", label: "Rubik Beastly" },
  // { value: "var(--font-sarabun)", label: "Sarabun" },
  // { value: "var(--font-bodoni-moda)", label: "Bodoni Moda" },
  // { value: "var(--font-acme)", label: "Acme" },
  // { value: "var(--font-abeezee)", label: "ABeeZee" },
  // { value: "var(--font-spectral)", label: "Spectral" },
  // { value: "var(--font-noto-sans-adlam)", label: "Noto Sans Adlam" },
  // { value: "var(--font-noto-sans-deseret)", label: "Noto Sans Deseret" },
  // { value: "var(--font-antic-slab)", label: "Antic Slab" },
  // { value: "var(--font-encode-sans)", label: "Encode Sans" },
  // { value: "var(--font-alegreya-sc)", label: "Alegreya SC" },
  // { value: "var(--font-concert-one)", label: "Concert One" },
  // { value: "var(--font-albert-sans)", label: "Albert Sans" },
  // { value: "var(--font-righteous)", label: "Righteous" },
  // { value: "var(--font-noticia-text)", label: "Noticia Text" },
  // { value: "var(--font-league-spartan)", label: "League Spartan" },
  // { value: "var(--font-montserrat-alternates)", label: "Montserrat Alternates" },
  // { value: "var(--font-tinos)", label: "Tinos" },
  // { value: "var(--font-yanone-kaffeesatz)", label: "Yanone Kaffeesatz" },
  // { value: "var(--font-prata)", label: "Prata" },
  // { value: "var(--font-chivo)", label: "Chivo" },
  // { value: "var(--font-russo-one)", label: "Russo One" },
  // { value: "var(--font-chango)", label: "Chango" },
  // { value: "var(--font-patua-one)", label: "Patua One" },
  // { value: "var(--font-parisienne)", label: "Parisienne" },
  // { value: "var(--font-sanchez)", label: "Sanchez" },
  // { value: "var(--font-cardo)", label: "Cardo" },
  // { value: "var(--font-comic-neue)", label: "Comic Neue" },
  // { value: "var(--font-press-start-2p)", label: "Press Start 2P" },
  // { value: "var(--font-merienda)", label: "Merienda" },
  // { value: "var(--font-ubuntu-sans)", label: "Ubuntu Sans" },
  // { value: "var(--font-luckiest-guy)", label: "Luckiest Guy" },
  // { value: "var(--font-creepster)", label: "Creepster" },
  // { value: "var(--font-gloria-hallelujah)", label: "Gloria Hallelujah" },
  // { value: "var(--font-philosopher)", label: "Philosopher" },
  // { value: "var(--font-yantramanav)", label: "Yantramanav" },
  // { value: "var(--font-gruppo)", label: "Gruppo" },
  // { value: "var(--font-onest)", label: "Onest" },
  // { value: "var(--font-crete-round)", label: "Crete Round" },
  // { value: "var(--font-alata)", label: "Alata" },
  // { value: "var(--font-ibm-plex-sans-condensed)", label: "IBM Plex Sans Condensed" },
  // { value: "var(--font-noto-sans-syriac-eastern)", label: "Noto Sans Syriac Eastern" },
  // { value: "var(--font-quattrocento)", label: "Quattrocento" },
  // { value: "var(--font-patrick-hand)", label: "Patrick Hand" },
  // { value: "var(--font-encode-sans-condensed)", label: "Encode Sans Condensed" },
  // { value: "var(--font-rokkitt)", label: "Rokkitt" },
  // { value: "var(--font-zeyada)", label: "Zeyada" },
  // { value: "var(--font-sen)", label: "Sen" },
  // { value: "var(--font-tenor-sans)", label: "Tenor Sans" },
  // { value: "var(--font-red-hat-display)", label: "Red Hat Display" },
  // { value: "var(--font-red-hat-text)", label: "Red Hat Text" },
  // { value: "var(--font-taviraj)", label: "Taviraj" },
  // { value: "var(--font-sofia-sans)", label: "Sofia Sans" },
  // { value: "var(--font-syncopate)", label: "Syncopate" },
  // { value: "var(--font-josefin-slab)", label: "Josefin Slab" },
  // { value: "var(--font-fira-sans-extra-condensed)", label: "Fira Sans Extra Condensed" }
];

export function FontSelector({ value, onChange }: FontSelectorProps) {
  const [open, setOpen] = useState(false)
  const [fonts] = useState<{ value: string; label: string }[]>(ALL_FONTS)
  const [searchTerm, setSearchTerm] = useState("")

  const filteredFonts = searchTerm
    ? fonts.filter((font) => font.label.toLowerCase().includes(searchTerm.toLowerCase()))
    : fonts

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Button
          variant="outline"
          role="combobox"
          aria-expanded={open}
          className="w-full justify-between"
          style={{ fontFamily: value }}
        >
          <span className="truncate">{value}</span>
          <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-full p-0">
        <Command>
          <CommandInput placeholder="Search fonts..." onValueChange={setSearchTerm} />
          <CommandList>
            <CommandEmpty>No font found.</CommandEmpty>
            <CommandGroup className="max-h-60 overflow-auto">
              {filteredFonts.map((font) => (
                <CommandItem
                  key={font.value}
                  value={font.label}
                  onSelect={() => {
                    onChange(font.label)
                    setOpen(false)
                  }}
                  style={{ fontFamily: font.value }}
                >
                  <Check className={cn("mr-2 h-4 w-4", value === font.value ? "opacity-100" : "opacity-0")} />
                  {font.label}
                </CommandItem>
              ))}
            </CommandGroup>
          </CommandList>
        </Command>
      </PopoverContent>
    </Popover>
  )
}

